// TODO: typeDescriptorFn should expect an allocator... The structure of Serializer makes no sense...
// TODO: add tempo conversion method to timestamp.zig
// TODO: formatting, better end of lines, use the format thing to not worry about indent.
// TODO: optimzie things?
// TODO: run test with config=asan...
// TODO: name conflict between generated variant names and subtypes, or even Kind...
// TODO: deduplicate serializer... defined both in serializers and serializer
// TODO: do not expose the adapter, only expose the serializer?
import {
  unquoteAndUnescape,
  type CodeGenerator,
  type Constant,
  type Field,
  type Module,
  type Record,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
  type Value,
} from "skir-internal";
import { z } from "zod";
import { KeyedArrayContext, type KeySpec } from "./keyed_array_context.js";
import {
  getDeclaredTypeName,
  modulePathToImportAlias,
  modulePathToOutputPath,
  toConstantName,
  toFieldGetterName,
  toStructFieldName,
  toVariantName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

const GENERATED_UNKNOWN_VARIANT_NAME = "Unknown";

class ZigCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-zig-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap } = input;
    const keyedArrayContext = new KeyedArrayContext(input.modules);
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToOutputPath(module.path),
        code: new ZigSourceFileGenerator(
          module,
          recordMap,
          keyedArrayContext,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Zig file.
class ZigSourceFileGenerator {
  private code = "";
  private readonly typeSpeller: TypeSpeller;
  private readonly keyedArrayContext: KeyedArrayContext;
  private readonly referencedModulePaths = new Set<string>();

  /**
   * Maps each Record object to its direct-child RecordLocations.
   * The key `null` holds top-level records (no parent).
   *
   * `module.records` is depth-first (children before parents), but we only
   * need grouping here — siblings retain their declaration order because
   * depth-first visits them in the same order they were declared.
   */
  private readonly childrenOf: Map<
    RecordLocation["record"] | null,
    RecordLocation[]
  > = new Map();

  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    keyedArrayContext: KeyedArrayContext,
  ) {
    this.keyedArrayContext = keyedArrayContext;
    this.typeSpeller = new TypeSpeller(
      recordMap,
      inModule.path,
      keyedArrayContext,
    );
    for (const loc of inModule.records) {
      const ancestors = loc.recordAncestors;
      // recordAncestors includes the record itself as the last element, so
      // the parent is at index length-2 (or null for top-level records).
      const parentRecord =
        ancestors.length > 1 ? (ancestors[ancestors.length - 2] ?? null) : null;
      const siblings = this.childrenOf.get(parentRecord) ?? [];
      siblings.push(loc);
      this.childrenOf.set(parentRecord, siblings);
    }
    for (const loc of inModule.records) {
      this.collectRecordImports(loc.record);
    }
    for (const constant of inModule.constants) {
      if (constant.type) {
        this.collectTypeImports(constant.type);
      }
    }
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
//  |  _  \\                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
//
// Generated by skir-zig-gen
// Home: https://github.com/gepheum/skir-zig-gen

`,
    );

    this.writeImports();

    for (const loc of this.childrenOf.get(null) ?? []) {
      this.writeRecord(loc);
    }

    if (this.inModule.constants.length > 0) {
      this.push("\n");
      for (const constant of this.inModule.constants) {
        this.writeConstant(constant);
      }
    }

    return this.joinLinesAndFixFormatting();
  }

  private writeRecord(loc: RecordLocation): void {
    if (loc.record.recordType === "struct") {
      this.writeStruct(loc);
      return;
    }
    this.writeEnum(loc);
  }

  private writeImports(): void {
    this.push(`const std = @import("std");\n`);
    this.push(
      `const skir_client = @import(${toZigStringLiteral(
        relativePathFromModule(this.inModule.path, null),
      )});\n`,
    );

    const importedModulePaths = [...this.referencedModulePaths].sort();
    for (const modulePath of importedModulePaths) {
      this.push(
        `const ${modulePathToImportAlias(modulePath)} = @import(${toZigStringLiteral(
          relativePathFromModule(this.inModule.path, modulePath),
        )});\n`,
      );
    }

    if (importedModulePaths.length > 0) {
      this.push("\n");
    } else {
      this.push("\n");
    }

    this.push(
      `const _SerializerInitState = enum { uninitialized, initializing, initialized };\n`,
    );
    this.push(`var _serializer_init_mutex: std.Thread.Mutex = .{};\n\n`);
  }

  private writeStruct(loc: RecordLocation): void {
    const typeName = getDeclaredTypeName(loc);
    const children = this.childrenOf.get(loc.record) ?? [];
    const keySpecs = this.keyedArrayContext.getKeySpecsForItemStruct(
      loc,
      this.typeSpeller,
    );

    this.push(commentify(docToCommentText(loc.record.doc)));
    this.push(`pub const ${typeName} = struct {\n`);

    for (const child of children) {
      this.writeRecord(child);
    }

    for (const field of loc.record.fields) {
      this.writeStructField(field);
    }

    this.push(
      `_unrecognized: ?skir_client.UnrecognizedFields(@This()) = null,\n`,
    );
    this.push(`pub const default: @This() = .{\n`);
    for (const field of loc.record.fields) {
      if (field.isRecursive !== false) {
        this.push(
          `.${this.getRecursiveStorageName(field)} = .default_value,\n`,
        );
      } else {
        this.push(
          `.${toStructFieldName(field.name.text)} = ${this.typeSpeller.getDefaultExpr(field.type!)},\n`,
        );
      }
    }
    this.push(`._unrecognized = null,\n`);
    this.push(`};\n`);

    const recursiveFields = loc.record.fields.filter(
      (field) => field.isRecursive !== false,
    );
    if (recursiveFields.length > 0) {
      for (const field of recursiveFields) {
        this.writeRecursiveFieldGetter(field);
      }
    }

    this.writeStructSerializer(loc, typeName);

    this.push(`};\n`);

    if (keySpecs.length > 0) {
      this.push(`\n`);
      for (const keySpec of keySpecs) {
        this.writeKeySpec(keySpec);
      }
    }
  }

  private writeEnum(loc: RecordLocation): void {
    const typeName = getDeclaredTypeName(loc);
    const children = this.childrenOf.get(loc.record) ?? [];
    const emitKindEnum = this.keyedArrayContext.isEnumUsedAsKey(loc.record);

    this.push(commentify(docToCommentText(loc.record.doc)));
    this.push(`pub const ${typeName} = union(enum) {\n`);

    for (const child of children) {
      this.writeRecord(child);
    }

    if (emitKindEnum) {
      this.push(`pub const Kind = enum {\n`);
      this.push(`${GENERATED_UNKNOWN_VARIANT_NAME},\n`);
      for (const variant of loc.record.fields) {
        this.push(`${toVariantName(variant.name.text)},\n`);
      }
      this.push(`};\n`);
    }

    this.push(
      `pub const default: @This() = .{ .${GENERATED_UNKNOWN_VARIANT_NAME} = .{} };\n`,
    );
    if (emitKindEnum) {
      this.push(`pub fn kind(self: @This()) Kind {\n`);
      this.push(`return switch (self) {\n`);
      this.push(
        `.${GENERATED_UNKNOWN_VARIANT_NAME} => .${GENERATED_UNKNOWN_VARIANT_NAME},\n`,
      );
      for (const variant of loc.record.fields) {
        const variantName = toVariantName(variant.name.text);
        this.push(`.${variantName} => .${variantName},\n`);
      }
      this.push(`};\n`);
      this.push(`}\n`);
    }

    this.push(
      `${GENERATED_UNKNOWN_VARIANT_NAME}: skir_client.UnrecognizedVariant(@This()),\n`,
    );
    for (const variant of loc.record.fields) {
      this.push(commentify(docToCommentText(variant.doc)));
      if (variant.type) {
        const variantType =
          variant.isRecursive !== false
            ? `*const ${this.typeSpeller.getZigType(variant.type)}`
            : this.typeSpeller.getZigType(variant.type);
        this.push(`${toVariantName(variant.name.text)}: ${variantType},\n`);
      } else {
        this.push(`${toVariantName(variant.name.text)},\n`);
      }
    }

    this.writeEnumSerializer(loc, typeName);

    this.push(`};\n`);
  }

  private writeStructField(field: Field): void {
    const comment = commentify(docToCommentText(field.doc));

    if (field.isRecursive !== false) {
      const storageName = this.getRecursiveStorageName(field);
      const rawType = this.typeSpeller.getZigType(field.type!);
      this.push(comment);
      this.push(`${storageName}: skir_client.Recursive(${rawType}),\n`);
      return;
    }

    const fieldName = toStructFieldName(field.name.text);
    const fieldType = this.typeSpeller.getZigType(field.type!);
    this.push(comment);
    this.push(`${fieldName}: ${fieldType},\n`);
  }

  private writeRecursiveFieldGetter(field: Field): void {
    const getterName = toFieldGetterName(field);
    const storageName = this.getRecursiveStorageName(field);
    const returnType = this.typeSpeller.getZigType(field.type!);
    const defaultExpr = this.typeSpeller.getDefaultExpr(field.type!);

    this.push(commentify(docToCommentText(field.doc)));
    this.push(`pub fn ${getterName}(self: *const @This()) ${returnType} {\n`);
    this.push(`return switch (self.${storageName}) {\n`);
    this.push(`.default_value => ${defaultExpr},\n`);
    this.push(`.value => |value| value.*,\n`);
    this.push(`};\n`);
    this.push(`}\n`);
  }

  private writeStructSerializer(loc: RecordLocation, _typeName: string): void {
    const qualifiedName = loc.recordAncestors.map((x) => x.name.text).join(".");

    this.push(`fn _adapter() *skir_client.StructAdapter(@This()) {\n`);
    this.push(`const S = @This();\n`);
    this.push(`const Holder = struct {\n`);
    this.push(`var state: _SerializerInitState = .uninitialized;\n`);
    this.push(`var adapter: skir_client.StructAdapter(S) = undefined;\n`);
    this.push(`};\n`);
    this.push(`_serializer_init_mutex.lock();\n`);
    this.push(`defer _serializer_init_mutex.unlock();\n`);
    this.push(`switch (Holder.state) {\n`);
    this.push(`.initialized, .initializing => return &Holder.adapter,\n`);
    this.push(`.uninitialized => {},\n`);
    this.push(`}\n`);
    this.push(`Holder.state = .initializing;\n`);
    this.push(`Holder.adapter = skir_client.StructAdapter(S).init(\n`);
    this.push(`std.heap.page_allocator,\n`);
    this.push(`${toZigStringLiteral(this.inModule.path)},\n`);
    this.push(`${toZigStringLiteral(qualifiedName)},\n`);
    this.push(`${toZigStringLiteral(docToCommentText(loc.record.doc))},\n`);
    this.push(
      `struct { fn get(x: *const S) ?skir_client.UnrecognizedFields(S) { return x._unrecognized; } }.get,\n`,
    );
    this.push(
      `struct { fn set(x: *S, u: ?skir_client.UnrecognizedFields(S)) void { x._unrecognized = u; } }.set,\n`,
    );
    this.push(`) catch unreachable;\n`);

    for (const removedNumber of loc.record.removedNumbers) {
      this.push(
        `Holder.adapter.addRemovedNumber(${removedNumber}) catch unreachable;\n`,
      );
    }

    for (const field of loc.record.fields) {
      const doc = toZigStringLiteral(docToCommentText(field.doc));
      if (field.isRecursive !== false) {
        const storageName = this.getRecursiveStorageName(field);
        const rawType = this.typeSpeller.getZigType(field.type!);
        const storageType = `skir_client.Recursive(${rawType})`;
        const fieldSerializer = `skir_client.recursiveSerializer(${rawType}, ${this.getSerializerExpr(field.type!, { maybeInitializingSameModule: true })})`;
        this.push(`Holder.adapter.addField(\n`);
        this.push(`${storageType},\n`);
        this.push(`${toZigStringLiteral(field.name.text)},\n`);
        this.push(`${field.number},\n`);
        this.push(`${fieldSerializer},\n`);
        this.push(`${doc},\n`);
        this.push(
          `struct { fn get(x: *const S) ${storageType} { return x.${storageName}; } }.get,\n`,
        );
        this.push(
          `struct { fn set(x: *S, v: ${storageType}) void { x.${storageName} = v; } }.set,\n`,
        );
        this.push(`) catch unreachable;\n`);
      } else {
        const fieldName = toStructFieldName(field.name.text);
        const fieldType = this.typeSpeller.getZigType(field.type!);
        this.push(`Holder.adapter.addField(\n`);
        this.push(`${fieldType},\n`);
        this.push(`${toZigStringLiteral(field.name.text)},\n`);
        this.push(`${field.number},\n`);
        this.push(
          `${this.getSerializerExpr(field.type!, { maybeInitializingSameModule: true })},\n`,
        );
        this.push(`${doc},\n`);
        this.push(
          `struct { fn get(x: *const S) ${fieldType} { return x.${fieldName}; } }.get,\n`,
        );
        this.push(
          `struct { fn set(x: *S, v: ${fieldType}) void { x.${fieldName} = v; } }.set,\n`,
        );
        this.push(`) catch unreachable;\n`);
      }
    }

    this.push(`Holder.adapter.finalize() catch unreachable;\n`);
    this.push(`Holder.state = .initialized;\n`);
    this.push(`return &Holder.adapter;\n`);
    this.push(`}\n`);

    this.push(
      `fn _maybeInitializingSerializer() skir_client.Serializer(@This()) {\n`,
    );
    this.push(
      `return skir_client.structSerializerFromStatic(@This(), @This()._adapter);\n`,
    );
    this.push(`}\n`);

    this.push(`pub fn serializer() skir_client.Serializer(@This()) {\n`);
    this.push(
      `if (@inComptime()) return @This()._maybeInitializingSerializer();\n`,
    );
    this.push(`_ = @This()._adapter();\n`);
    this.push(`return @This()._maybeInitializingSerializer();\n`);
    this.push(`}\n`);
  }

  private writeEnumSerializer(loc: RecordLocation, _typeName: string): void {
    const qualifiedName = loc.recordAncestors.map((x) => x.name.text).join(".");

    this.push(`fn _adapter() *skir_client.EnumAdapter(@This()) {\n`);
    this.push(`const S = @This();\n`);
    this.push(`const Holder = struct {\n`);
    this.push(`var state: _SerializerInitState = .uninitialized;\n`);
    this.push(`var adapter: skir_client.EnumAdapter(S) = undefined;\n`);
    this.push(`};\n`);
    this.push(`_serializer_init_mutex.lock();\n`);
    this.push(`defer _serializer_init_mutex.unlock();\n`);
    this.push(`switch (Holder.state) {\n`);
    this.push(`.initialized, .initializing => return &Holder.adapter,\n`);
    this.push(`.uninitialized => {},\n`);
    this.push(`}\n`);
    this.push(`Holder.state = .initializing;\n`);
    this.push(`Holder.adapter = skir_client.EnumAdapter(S).init(\n`);
    this.push(`std.heap.page_allocator,\n`);
    this.push(`${toZigStringLiteral(this.inModule.path)},\n`);
    this.push(`${toZigStringLiteral(qualifiedName)},\n`);
    this.push(`${toZigStringLiteral(docToCommentText(loc.record.doc))},\n`);
    this.push(`struct {\n`);
    this.push(`fn getKindOrdinal(x: *const S) usize {\n`);
    this.push(`return switch (x.*) {\n`);
    this.push(`.${GENERATED_UNKNOWN_VARIANT_NAME} => 0,\n`);
    let kindOrdinal = 1;
    for (const variant of loc.record.fields) {
      this.push(`.${toVariantName(variant.name.text)} => ${kindOrdinal},\n`);
      kindOrdinal += 1;
    }
    this.push(`};\n`);
    this.push(`}\n`);
    this.push(`}.getKindOrdinal,\n`);
    this.push(
      `struct { fn wrapUnknown(u: skir_client.UnrecognizedVariant(S)) S { return .{ .${GENERATED_UNKNOWN_VARIANT_NAME} = u }; } }.wrapUnknown,\n`,
    );
    this.push(`struct {\n`);
    this.push(
      `fn getUnknown(x: *const S) ?skir_client.UnrecognizedVariant(S) {\n`,
    );
    this.push(`return switch (x.*) {\n`);
    this.push(`.${GENERATED_UNKNOWN_VARIANT_NAME} => |u| u,\n`);
    this.push(`else => null,\n`);
    this.push(`};\n`);
    this.push(`}\n`);
    this.push(`}.getUnknown,\n`);
    this.push(`) catch unreachable;\n`);

    for (const removedNumber of loc.record.removedNumbers) {
      this.push(
        `Holder.adapter.addRemovedNumber(${removedNumber}) catch unreachable;\n`,
      );
    }

    kindOrdinal = 1;
    for (const variant of loc.record.fields) {
      const variantName = toVariantName(variant.name.text);
      const doc = toZigStringLiteral(docToCommentText(variant.doc));
      if (variant.type) {
        const rawType = this.typeSpeller.getZigType(variant.type);
        const payloadType =
          variant.isRecursive !== false ? `*const ${rawType}` : rawType;
        const serializerExpr =
          variant.isRecursive !== false
            ? `skir_client.pointerSerializer(${rawType}, ${this.getSerializerExpr(variant.type, { maybeInitializingSameModule: true })})`
            : this.getSerializerExpr(variant.type, {
                maybeInitializingSameModule: true,
              });
        this.push(`Holder.adapter.addWrapperVariant(\n`);
        this.push(`${payloadType},\n`);
        this.push(`${toZigStringLiteral(variant.name.text)},\n`);
        this.push(`${variant.number},\n`);
        this.push(`${kindOrdinal},\n`);
        this.push(`${serializerExpr},\n`);
        this.push(`${doc},\n`);
        this.push(
          `struct { fn wrap(v: ${payloadType}) S { return .{ .${variantName} = v }; } }.wrap,\n`,
        );
        this.push(`struct {\n`);
        this.push(`fn getValue(x: *const S) ${payloadType} {\n`);
        this.push(`return switch (x.*) {\n`);
        this.push(`.${variantName} => |v| v,\n`);
        this.push(`else => unreachable,\n`);
        this.push(`};\n`);
        this.push(`}\n`);
        this.push(`}.getValue,\n`);
        this.push(`) catch unreachable;\n`);
      } else {
        this.push(
          `Holder.adapter.addConstantVariant(${toZigStringLiteral(variant.name.text)}, ${variant.number}, ${kindOrdinal}, ${doc}, @as(S, .${variantName})) catch unreachable;\n`,
        );
      }
      kindOrdinal += 1;
    }

    this.push(`Holder.adapter.finalize() catch unreachable;\n`);
    this.push(`Holder.state = .initialized;\n`);
    this.push(`return &Holder.adapter;\n`);
    this.push(`}\n`);

    this.push(
      `fn _maybeInitializingSerializer() skir_client.Serializer(@This()) {\n`,
    );
    this.push(
      `return skir_client.enumSerializerFromStatic(@This(), @This()._adapter);\n`,
    );
    this.push(`}\n`);

    this.push(`pub fn serializer() skir_client.Serializer(@This()) {\n`);
    this.push(
      `if (@inComptime()) return @This()._maybeInitializingSerializer();\n`,
    );
    this.push(`_ = @This()._adapter();\n`);
    this.push(`return @This()._maybeInitializingSerializer();\n`);
    this.push(`}\n`);
  }

  private getSerializerExpr(
    type: ResolvedType,
    options: { maybeInitializingSameModule?: boolean } = {},
  ): string {
    switch (type.kind) {
      case "primitive":
        return this.getPrimitiveSerializerExpr(type.primitive);
      case "optional":
        return `skir_client.optionalSerializer(${this.typeSpeller.getZigType(type.other)}, ${this.getSerializerExpr(type.other, options)})`;
      case "array": {
        const inner = this.getSerializerExpr(type.item, options);
        if (type.key) {
          const spec = this.keyedArrayContext.getKeySpecForArrayType(
            type,
            this.typeSpeller,
          );
          if (spec) {
            return `skir_client.keyedArraySerializer(${spec.specRef}, ${inner})`;
          }
        }
        return `skir_client.arraySerializer(${this.typeSpeller.getZigType(type.item)}, ${inner})`;
      }
      case "record": {
        const typeName = this.typeSpeller.getZigType(type);
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        if (
          options.maybeInitializingSameModule &&
          recordLocation.modulePath === this.inModule.path
        ) {
          return `${typeName}._maybeInitializingSerializer()`;
        }
        return `${typeName}.serializer()`;
      }
    }
  }

  private getPrimitiveSerializerExpr(
    primitive:
      | "bool"
      | "int32"
      | "int64"
      | "hash64"
      | "float32"
      | "float64"
      | "timestamp"
      | "string"
      | "bytes",
  ): string {
    switch (primitive) {
      case "bool":
        return "skir_client.boolSerializer()";
      case "int32":
        return "skir_client.int32Serializer()";
      case "int64":
        return "skir_client.int64Serializer()";
      case "hash64":
        return "skir_client.hash64Serializer()";
      case "float32":
        return "skir_client.float32Serializer()";
      case "float64":
        return "skir_client.float64Serializer()";
      case "timestamp":
        return "skir_client.timestampSerializer()";
      case "string":
        return "skir_client.stringSerializer()";
      case "bytes":
        return "skir_client.bytesSerializer()";
    }
  }

  private writeKeySpec(keySpec: KeySpec): void {
    this.push(`pub const ${keySpec.specName} = struct {\n`);
    this.push(`pub const Value = ${keySpec.valueType};\n`);
    this.push(`pub const Key = ${keySpec.zigKeyType};\n`);
    this.push(`pub fn getGet(item: Value) Key {\n`);
    this.push(`return ${keySpec.zigKeyExpr};\n`);
    this.push(`}\n`);
    this.push(`pub fn defaultValue() *Value {\n`);
    this.push(`return @constCast(&Value.default);\n`);
    this.push(`}\n`);
    this.push(`pub fn keyExtractor() []const u8 {\n`);
    this.push(`return ${toZigStringLiteral(keySpec.keyExtractor)};\n`);
    this.push(`}\n`);
    this.push(`};\n`);
  }

  private writeConstant(constant: Constant): void {
    if (!constant.type) {
      return;
    }

    if (!this.typeContainsKeyedArray(constant.type)) {
      this.writeConstValueConstant(constant, constant.type);
      return;
    }

    this.writeLazyConstant(constant, constant.type);
  }

  private writeConstValueConstant(
    constant: Constant,
    type: ResolvedType,
  ): void {
    const zigName = toConstantName(constant.name.text);
    const zigType = this.typeSpeller.getZigType(type);
    const constExpr = this.valueToZigExpr(constant.value, type);

    this.push(commentify(docToCommentText(constant.doc)));
    this.push(`pub const ${zigName}: ${zigType} = ${constExpr};\n\n`);
  }

  private writeLazyConstant(constant: Constant, type: ResolvedType): void {
    if (constant.valueAsDenseJson === undefined) {
      return;
    }

    const zigName = toConstantName(constant.name.text);
    const zigType = this.typeSpeller.getZigType(type);
    const serializerExpr = this.getSerializerExpr(type);
    const denseJson = JSON.stringify(constant.valueAsDenseJson);

    this.push(commentify(docToCommentText(constant.doc)));
    this.push(`pub fn ${zigName}() *const ${zigType} {\n`);
    this.push(`const Holder = struct {\n`);
    this.push(`var mutex: std.Thread.Mutex = .{};\n`);
    this.push(`var initialized: bool = false;\n`);
    this.push(`var value: ${zigType} = undefined;\n`);
    this.push(`};\n`);
    this.push(`Holder.mutex.lock();\n`);
    this.push(`defer Holder.mutex.unlock();\n`);
    this.push(`if (!Holder.initialized) {\n`);
    this.push(`Holder.value = ${serializerExpr}.deserialize(\n`);
    this.push(`std.heap.page_allocator,\n`);
    this.push(`${toZigStringLiteral(denseJson)},\n`);
    this.push(`.{ .keepUnrecognizedValues = false },\n`);
    this.push(`) catch unreachable;\n`);
    this.push(`Holder.initialized = true;\n`);
    this.push(`}\n`);
    this.push(`return &Holder.value;\n`);
    this.push(`}\n\n`);
  }

  private typeContainsKeyedArray(
    type: ResolvedType,
    seenRecords: Set<RecordKey> = new Set(),
  ): boolean {
    switch (type.kind) {
      case "primitive":
        return false;
      case "optional":
        return this.typeContainsKeyedArray(type.other, seenRecords);
      case "array":
        return (
          !!type.key || this.typeContainsKeyedArray(type.item, seenRecords)
        );
      case "record": {
        if (seenRecords.has(type.key)) {
          return false;
        }
        seenRecords.add(type.key);
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        for (const field of recordLocation.record.fields) {
          if (
            field.type &&
            this.typeContainsKeyedArray(field.type, seenRecords)
          ) {
            return true;
          }
        }
        return false;
      }
    }
  }

  private valueToZigExpr(value: Value, type: ResolvedType): string {
    switch (type.kind) {
      case "primitive":
        return this.primitiveToZigExpr(value, type.primitive);
      case "optional": {
        if (value.kind === "literal" && value.token.text === "null") {
          return "null";
        }
        return this.valueToZigExpr(value, type.other);
      }
      case "array": {
        if (value.kind !== "array") {
          throw new Error("Expected array value for array constant");
        }
        if (value.items.length === 0) {
          return "&.{}";
        }
        const items = value.items.map((item) =>
          this.valueToZigExpr(item, type.item),
        );
        return `&.{\n${items.join(",\n")}\n}`;
      }
      case "record": {
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        if (recordLocation.record.recordType === "struct") {
          return this.structValueToZigExpr(value, recordLocation);
        }
        return this.enumValueToZigExpr(value, recordLocation);
      }
    }
  }

  private primitiveToZigExpr(
    value: Value,
    primitive:
      | "bool"
      | "int32"
      | "int64"
      | "hash64"
      | "float32"
      | "float64"
      | "timestamp"
      | "string"
      | "bytes",
  ): string {
    if (value.kind !== "literal") {
      throw new Error(`Expected literal for primitive ${primitive}`);
    }
    const tokenText = value.token.text;

    switch (primitive) {
      case "bool":
      case "int32":
      case "int64":
      case "hash64":
        return tokenText;
      case "float32":
        return this.floatTokenToZigExpr(tokenText, "f32");
      case "float64":
        return this.floatTokenToZigExpr(tokenText, "f64");
      case "timestamp": {
        const ms = new Date(unquoteAndUnescape(tokenText)).getTime();
        if (Number.isNaN(ms)) {
          throw new Error(`Cannot parse timestamp constant: ${tokenText}`);
        }
        return `.{ .unix_millis = ${Math.trunc(ms)} }`;
      }
      case "string":
        return toZigStringLiteral(unquoteAndUnescape(tokenText));
      case "bytes": {
        const raw = unquoteAndUnescape(tokenText);
        const hex = raw.startsWith("hex:") ? raw.slice(4) : raw;
        if (hex.length === 0) {
          return '""';
        }
        const bytes: string[] = [];
        for (let i = 0; i < hex.length; i += 2) {
          const pair = hex.slice(i, i + 2);
          bytes.push(`0x${pair.toLowerCase()}`);
        }
        return `&.{ ${bytes.join(", ")} }`;
      }
    }
  }

  private floatTokenToZigExpr(
    tokenText: string,
    typeName: "f32" | "f64",
  ): string {
    if (!tokenText.startsWith('"') && !tokenText.startsWith("'")) {
      return tokenText;
    }
    const special = unquoteAndUnescape(tokenText);
    switch (special) {
      case "Infinity":
        return `std.math.inf(${typeName})`;
      case "-Infinity":
        return `-std.math.inf(${typeName})`;
      case "NaN":
        return `std.math.nan(${typeName})`;
      default:
        return tokenText;
    }
  }

  private structValueToZigExpr(value: Value, record: RecordLocation): string {
    if (value.kind !== "object") {
      throw new Error("Expected object for struct constant");
    }

    const entries: string[] = [];
    for (const field of record.record.fields) {
      if (!field.type) continue;
      const fieldEntry = value.entries[field.name.text];
      if (field.isRecursive !== false) {
        const storageName = this.getRecursiveStorageName(field);
        if (fieldEntry) {
          const innerType = this.typeSpeller.getZigType(field.type);
          const innerExpr = this.valueToZigExpr(fieldEntry.value, field.type);
          entries.push(
            `.${storageName} = .{ .value = &@as(${innerType}, ${innerExpr}) }`,
          );
        } else {
          entries.push(`.${storageName} = .default_value`);
        }
      } else {
        const fieldName = toStructFieldName(field.name.text);
        const fieldExpr = fieldEntry
          ? this.valueToZigExpr(fieldEntry.value, field.type)
          : this.typeSpeller.getDefaultExpr(field.type);
        entries.push(`.${fieldName} = ${fieldExpr}`);
      }
    }
    entries.push(`._unrecognized = null`);

    return `.{\n${entries.join(",\n")}\n}`;
  }

  private enumValueToZigExpr(value: Value, record: RecordLocation): string {
    if (value.kind === "literal") {
      const variantName = unquoteAndUnescape(value.token.text);
      const declaration = record.record.nameToDeclaration[variantName];
      if (!declaration || declaration.kind !== "field") {
        return `.{ .${GENERATED_UNKNOWN_VARIANT_NAME} = .{} }`;
      }
      const zigVariant = toVariantName(declaration.name.text);
      if (declaration.type) {
        return `.{ .${zigVariant} = ${this.typeSpeller.getDefaultExpr(declaration.type)} }`;
      }
      return `.${zigVariant}`;
    }

    if (value.kind !== "object") {
      throw new Error("Expected object for enum wrapper constant");
    }

    const kindEntry = value.entries["kind"];
    if (!kindEntry || kindEntry.value.kind !== "literal") {
      throw new Error("Expected enum object to have literal kind");
    }
    const variantName = unquoteAndUnescape(kindEntry.value.token.text);
    const declaration = record.record.nameToDeclaration[variantName];
    if (!declaration || declaration.kind !== "field") {
      return `.{ .${GENERATED_UNKNOWN_VARIANT_NAME} = .{} }`;
    }

    const zigVariant = toVariantName(declaration.name.text);
    if (!declaration.type) {
      return `.${zigVariant}`;
    }

    const payloadEntry = value.entries["value"];
    const payloadExpr = payloadEntry
      ? this.valueToZigExpr(payloadEntry.value, declaration.type)
      : this.typeSpeller.getDefaultExpr(declaration.type);
    if (declaration.isRecursive !== false) {
      const rawType = this.typeSpeller.getZigType(declaration.type);
      return `.{ .${zigVariant} = &@as(${rawType}, ${payloadExpr}) }`;
    }
    return `.{ .${zigVariant} = ${payloadExpr} }`;
  }

  private getRecursiveStorageName(field: Field): string {
    return `_${toStructFieldName(field.name.text)}`;
  }

  private collectRecordImports(record: Record): void {
    for (const field of record.fields) {
      if (field.type) {
        this.collectTypeImports(field.type);
      }
    }
  }

  private collectTypeImports(type: ResolvedType): void {
    switch (type.kind) {
      case "primitive":
        return;
      case "optional":
        this.collectTypeImports(type.other);
        return;
      case "array":
        this.collectTypeImports(type.item);
        if (type.key?.keyType.kind === "record") {
          this.collectTypeImports(type.key.keyType);
        }
        return;
      case "record": {
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        if (recordLocation.modulePath !== this.inModule.path) {
          this.referencedModulePaths.add(recordLocation.modulePath);
        }
      }
    }
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "  ";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string | undefined =>
      contextStack[contextStack.length - 1];
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("//") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        // Remove trailing newline.
        .replace(/\n\n$/g, "\n")
    );
  }
}

function relativePathFromModule(
  fromModulePath: string,
  toModulePath: string | null,
): string {
  const fromFile = `src/skirout/${modulePathToOutputPath(fromModulePath)}`;
  const toFile = toModulePath
    ? `src/skirout/${modulePathToOutputPath(toModulePath)}`
    : "src/skir_client.zig";
  const fromDir = fromFile.slice(0, fromFile.lastIndexOf("/"));
  const fromParts = fromDir.split("/");
  const toParts = toFile.split("/");
  let common = 0;
  while (common < fromParts.length && fromParts[common] === toParts[common]) {
    common++;
  }
  const up = fromParts.length - common;
  const rel = [...Array(up).fill(".."), ...toParts.slice(common)].join("/");
  return rel.length > 0 ? rel : ".";
}

function commentify(text: string, indent = ""): string {
  if (!text) {
    return "";
  }
  return text
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => `${indent}/// ${line.trim()}\n`)
    .join("");
}

function docToCommentText(doc: { text: string }): string {
  return doc.text.trim();
}

function toZigStringLiteral(input: string): string {
  return JSON.stringify(input);
}

export const GENERATOR = new ZigCodeGenerator();
