// TODO: formatting, better end of lines, use the format thing to not worry about indent.
// TODO: name conflict between generated variant names and subtypes, or even Kind...
// TODO: no import node:path

import { posix as pathPosix } from "node:path";
import {
  type CodeGenerator,
  type Field,
  type Module,
  type Record,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
} from "skir-internal";
import { z } from "zod";
import { KeyedArrayContext, type KeySpec } from "./keyed_array_context.js";
import {
  modulePathToImportAlias,
  modulePathToOutputPath,
  toFieldGetterName,
  toStructFieldName,
  toTypeName,
  toVariantName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

const GENERATED_UNKNOWN_VARIANT_NAME = "Unknown";

class ZigCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-zig-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap } = input;
    const keyedArrayContext = new KeyedArrayContext(input.modules);
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToOutputPath(module.path),
        code: new ZigSourceFileGenerator(
          module,
          recordMap,
          keyedArrayContext,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Zig file.
class ZigSourceFileGenerator {
  private readonly parts: string[] = [];
  private readonly typeSpeller: TypeSpeller;
  private readonly keyedArrayContext: KeyedArrayContext;
  private readonly referencedModulePaths = new Set<string>();

  /**
   * Maps each Record object to its direct-child RecordLocations.
   * The key `null` holds top-level records (no parent).
   *
   * `module.records` is depth-first (children before parents), but we only
   * need grouping here — siblings retain their declaration order because
   * depth-first visits them in the same order they were declared.
   */
  private readonly childrenOf: Map<
    RecordLocation["record"] | null,
    RecordLocation[]
  > = new Map();

  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    keyedArrayContext: KeyedArrayContext,
  ) {
    this.keyedArrayContext = keyedArrayContext;
    this.typeSpeller = new TypeSpeller(
      recordMap,
      inModule.path,
      keyedArrayContext,
    );
    for (const loc of inModule.records) {
      const ancestors = loc.recordAncestors;
      // recordAncestors includes the record itself as the last element, so
      // the parent is at index length-2 (or null for top-level records).
      const parentRecord =
        ancestors.length > 1 ? (ancestors[ancestors.length - 2] ?? null) : null;
      const siblings = this.childrenOf.get(parentRecord) ?? [];
      siblings.push(loc);
      this.childrenOf.set(parentRecord, siblings);
    }
    for (const loc of inModule.records) {
      this.collectRecordImports(loc.record);
    }
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
//  |  _  \\                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
//
// Generated by skir-zig-gen
// Home: https://github.com/gepheum/skir-zig-gen

`,
    );

    this.writeImports();

    for (const loc of this.childrenOf.get(null) ?? []) {
      this.writeRecord(loc, "");
    }

    return this.parts.join("");
  }

  private writeRecord(loc: RecordLocation, indent: string): void {
    if (loc.record.recordType === "struct") {
      this.writeStruct(loc, indent);
      return;
    }
    this.writeEnum(loc, indent);
  }

  private writeImports(): void {
    this.push(
      `const skir_client = @import(${toZigStringLiteral(
        relativePathFromModule(this.inModule.path, null),
      )});\n`,
    );

    const importedModulePaths = [...this.referencedModulePaths].sort();
    for (const modulePath of importedModulePaths) {
      this.push(
        `const ${modulePathToImportAlias(modulePath)} = @import(${toZigStringLiteral(
          relativePathFromModule(this.inModule.path, modulePath),
        )});\n`,
      );
    }

    if (importedModulePaths.length > 0) {
      this.push("\n");
    } else {
      this.push("\n");
    }
  }

  private writeStruct(loc: RecordLocation, indent: string): void {
    const typeName = toTypeName(loc.record.name.text);
    const children = this.childrenOf.get(loc.record) ?? [];
    const keySpecs = this.keyedArrayContext.getKeySpecsForItemStruct(
      loc,
      this.typeSpeller,
    );

    this.push(commentify(docToCommentText(loc.record.doc), indent));
    this.push(`${indent}pub const ${typeName} = struct {\n`);
    this.push("\n");

    for (const child of children) {
      this.writeRecord(child, indent + "    ");
    }
    if (children.length > 0) {
      this.push("\n");
    }

    for (const field of loc.record.fields) {
      if (field.isRecursive !== false) {
        this.writeRecursiveFieldType(field, indent + "    ");
      }
    }
    if (loc.record.fields.some((field) => field.isRecursive !== false)) {
      this.push("\n");
    }

    for (const field of loc.record.fields) {
      this.writeStructField(field, indent + "    ");
    }

    this.push(
      `${indent}    _unrecognized: ?skir_client.UnrecognizedFields = null,\n\n`,
    );
    this.push(`${indent}    pub const DEFAULT: @This() = .{\n`);
    for (const field of loc.record.fields) {
      if (field.isRecursive !== false) {
        this.push(
          `${indent}        .${this.getRecursiveStorageName(field)} = .default_value,\n`,
        );
      } else {
        this.push(
          `${indent}        .${toStructFieldName(field.name.text)} = ${this.typeSpeller.getDefaultExpr(field.type!)},\n`,
        );
      }
    }
    this.push(`${indent}        ._unrecognized = null,\n`);
    this.push(`${indent}    };\n\n`);

    const recursiveFields = loc.record.fields.filter(
      (field) => field.isRecursive !== false,
    );
    if (recursiveFields.length > 0) {
      this.push("\n");
      for (const field of recursiveFields) {
        this.writeRecursiveFieldGetter(field, indent + "    ");
      }
    }

    this.push(`${indent}};\n`);

    if (keySpecs.length > 0) {
      this.push("\n");
      for (const keySpec of keySpecs) {
        this.writeKeySpec(keySpec, indent);
      }
    }
  }

  private writeEnum(loc: RecordLocation, indent: string): void {
    const typeName = toTypeName(loc.record.name.text);
    const children = this.childrenOf.get(loc.record) ?? [];
    const variantNamesNeedSuffix = doVariantNamesNeedSuffix(loc.record.fields);
    const emitKindEnum = this.keyedArrayContext.isEnumUsedAsKey(loc.record);

    this.push(commentify(docToCommentText(loc.record.doc), indent));
    this.push(`${indent}pub const ${typeName} = union(enum) {\n`);
    this.push("\n");

    for (const child of children) {
      this.writeRecord(child, indent + "    ");
    }
    if (children.length > 0) {
      this.push("\n");
    }

    if (emitKindEnum) {
      this.push(`${indent}    pub const Kind = enum {\n`);
      this.push(`${indent}        ${GENERATED_UNKNOWN_VARIANT_NAME},\n`);
      for (const variant of loc.record.fields) {
        this.push(
          `${indent}        ${getRenderedVariantName(variant, variantNamesNeedSuffix)},\n`,
        );
      }
      this.push(`${indent}    };\n\n`);
    }

    this.push(
      `${indent}    pub const DEFAULT: @This() = .{ .${GENERATED_UNKNOWN_VARIANT_NAME} = .{} };\n\n`,
    );
    if (emitKindEnum) {
      this.push(`${indent}    pub fn kind(self: @This()) Kind {\n`);
      this.push(`${indent}        return switch (self) {\n`);
      this.push(
        `${indent}            .${GENERATED_UNKNOWN_VARIANT_NAME} => .${GENERATED_UNKNOWN_VARIANT_NAME},\n`,
      );
      for (const variant of loc.record.fields) {
        const variantName = getRenderedVariantName(
          variant,
          variantNamesNeedSuffix,
        );
        this.push(`${indent}            .${variantName} => .${variantName},\n`);
      }
      this.push(`${indent}        };\n`);
      this.push(`${indent}    }\n\n`);
    }

    this.push(
      `${indent}    ${GENERATED_UNKNOWN_VARIANT_NAME}: skir_client.UnrecognizedVariant,\n`,
    );
    for (const variant of loc.record.fields) {
      this.push(commentify(docToCommentText(variant.doc), `${indent}    `));
      if (variant.type) {
        const variantType =
          variant.isRecursive !== false
            ? `*const ${this.typeSpeller.getZigType(variant.type)}`
            : this.typeSpeller.getZigType(variant.type);
        this.push(
          `${indent}    ${getRenderedVariantName(variant, variantNamesNeedSuffix)}: ${variantType},\n`,
        );
      } else {
        this.push(
          `${indent}    ${getRenderedVariantName(variant, variantNamesNeedSuffix)},\n`,
        );
      }
    }
    this.push(`${indent}};\n`);
  }

  private writeStructField(field: Field, indent: string): void {
    const comment = commentify(docToCommentText(field.doc), indent);

    if (field.isRecursive !== false) {
      const storageName = this.getRecursiveStorageName(field);
      this.push(comment);
      this.push(
        `${indent}${storageName}: ${this.getRecursiveTypeName(field)},\n\n`,
      );
      return;
    }

    const fieldName = toStructFieldName(field.name.text);
    const fieldType = this.typeSpeller.getZigType(field.type!);
    this.push(comment);
    this.push(`${indent}${fieldName}: ${fieldType},\n\n`);
  }

  private writeRecursiveFieldGetter(field: Field, indent: string): void {
    const getterName = toFieldGetterName(field);
    const storageName = this.getRecursiveStorageName(field);
    const returnType = this.typeSpeller.getZigType(field.type!);
    const defaultExpr = this.typeSpeller.getDefaultExpr(field.type!);

    this.push(commentify(docToCommentText(field.doc), indent));
    this.push(
      `${indent}pub fn ${getterName}(self: *const @This()) ${returnType} {\n`,
    );
    this.push(`${indent}    return switch (self.${storageName}) {\n`);
    this.push(`${indent}        .default_value => ${defaultExpr},\n`);
    this.push(`${indent}        .value => |value| value.*,\n`);
    this.push(`${indent}    };\n`);
    this.push(`${indent}}\n\n`);
  }

  private writeRecursiveFieldType(field: Field, indent: string): void {
    const recursiveTypeName = this.getRecursiveTypeName(field);
    const rawType = this.typeSpeller.getZigType(field.type!);

    this.push(`${indent}pub const ${recursiveTypeName} = union(enum) {\n`);
    this.push(`${indent}    default_value,\n`);
    this.push(`${indent}    value: *const ${rawType},\n`);
    this.push(`${indent}};\n\n`);
  }

  private writeKeySpec(keySpec: KeySpec, indent: string): void {
    this.push(`${indent}pub const ${keySpec.specName} = struct {\n`);
    this.push(`${indent}    pub const Value = ${keySpec.valueType};\n`);
    this.push(`${indent}    pub const Key = ${keySpec.zigKeyType};\n\n`);
    this.push(`${indent}    pub fn getGet(item: Value) Key {\n`);
    this.push(`${indent}        return ${keySpec.zigKeyExpr};\n`);
    this.push(`${indent}    }\n\n`);
    this.push(`${indent}    pub fn defaultValue() *Value {\n`);
    this.push(`${indent}        return @constCast(&Value.DEFAULT);\n`);
    this.push(`${indent}    }\n\n`);
    this.push(`${indent}    pub fn keyExtractor() []const u8 {\n`);
    this.push(
      `${indent}        return ${toZigStringLiteral(keySpec.keyExtractor)};\n`,
    );
    this.push(`${indent}    }\n`);
    this.push(`${indent}};\n\n`);
  }

  private getRecursiveStorageName(field: Field): string {
    return `_${toStructFieldName(field.name.text)}`;
  }

  private getRecursiveTypeName(field: Field): string {
    return `${toTypeName(field.name.text)}Recursive`;
  }

  private collectRecordImports(record: Record): void {
    for (const field of record.fields) {
      if (field.type) {
        this.collectTypeImports(field.type);
      }
    }
  }

  private collectTypeImports(type: ResolvedType): void {
    switch (type.kind) {
      case "primitive":
        return;
      case "optional":
        this.collectTypeImports(type.other);
        return;
      case "array":
        this.collectTypeImports(type.item);
        if (type.key?.keyType.kind === "record") {
          this.collectTypeImports(type.key.keyType);
        }
        return;
      case "record": {
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        if (recordLocation.modulePath !== this.inModule.path) {
          this.referencedModulePaths.add(recordLocation.modulePath);
        }
      }
    }
  }

  private push(...parts: string[]): void {
    for (const part of parts) {
      this.parts.push(part);
    }
  }
}

function doVariantNamesNeedSuffix(variants: readonly Field[]): boolean {
  const seenNames = new Set<string>();
  for (const variant of variants) {
    const name = toVariantName(variant.name.text);
    if (name === GENERATED_UNKNOWN_VARIANT_NAME || seenNames.has(name)) {
      return true;
    }
    seenNames.add(name);
  }
  return false;
}

function getRenderedVariantName(field: Field, suffixNeeded: boolean): string {
  const baseName = toVariantName(field.name.text);
  if (!suffixNeeded) {
    return baseName;
  }
  return `${baseName}${field.type ? "Wrapper" : "Const"}`;
}

function relativePathFromModule(
  fromModulePath: string,
  toModulePath: string | null,
): string {
  const fromFile = pathPosix.join(
    "src",
    "skirout",
    modulePathToOutputPath(fromModulePath),
  );
  const toFile = toModulePath
    ? pathPosix.join("src", "skirout", modulePathToOutputPath(toModulePath))
    : pathPosix.join("src", "skir_client.zig");
  const relative = pathPosix.relative(pathPosix.dirname(fromFile), toFile);
  return relative.length > 0 ? relative : ".";
}

function commentify(text: string, indent = ""): string {
  if (!text) {
    return "";
  }
  return text
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => `${indent}/// ${line.trim()}\n`)
    .join("");
}

function docToCommentText(doc: { text: string }): string {
  return doc.text.trim();
}

function toZigStringLiteral(input: string): string {
  return JSON.stringify(input);
}

export const GENERATOR = new ZigCodeGenerator();
