// TODO: formatting, better end of lines, use the format thing to not worry about indent.
// TODO: name conflict between generated variant names and subtypes, or even Kind...
// TODO: deduplicate serializer... defined both in serializers and serializer
import {
  type CodeGenerator,
  type Field,
  type Module,
  type Record,
  type RecordKey,
  type RecordLocation,
  type ResolvedType,
} from "skir-internal";
import { z } from "zod";
import { KeyedArrayContext, type KeySpec } from "./keyed_array_context.js";
import {
  getDeclaredTypeName,
  modulePathToImportAlias,
  modulePathToOutputPath,
  toFieldGetterName,
  toStructFieldName,
  toTypeName,
  toVariantName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

const GENERATED_UNKNOWN_VARIANT_NAME = "Unknown";

class ZigCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-zig-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const { recordMap } = input;
    const keyedArrayContext = new KeyedArrayContext(input.modules);
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToOutputPath(module.path),
        code: new ZigSourceFileGenerator(
          module,
          recordMap,
          keyedArrayContext,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Zig file.
class ZigSourceFileGenerator {
  private code = "";
  private readonly typeSpeller: TypeSpeller;
  private readonly keyedArrayContext: KeyedArrayContext;
  private readonly referencedModulePaths = new Set<string>();

  /**
   * Maps each Record object to its direct-child RecordLocations.
   * The key `null` holds top-level records (no parent).
   *
   * `module.records` is depth-first (children before parents), but we only
   * need grouping here — siblings retain their declaration order because
   * depth-first visits them in the same order they were declared.
   */
  private readonly childrenOf: Map<
    RecordLocation["record"] | null,
    RecordLocation[]
  > = new Map();

  constructor(
    private readonly inModule: Module,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
    keyedArrayContext: KeyedArrayContext,
  ) {
    this.keyedArrayContext = keyedArrayContext;
    this.typeSpeller = new TypeSpeller(
      recordMap,
      inModule.path,
      keyedArrayContext,
    );
    for (const loc of inModule.records) {
      const ancestors = loc.recordAncestors;
      // recordAncestors includes the record itself as the last element, so
      // the parent is at index length-2 (or null for top-level records).
      const parentRecord =
        ancestors.length > 1 ? (ancestors[ancestors.length - 2] ?? null) : null;
      const siblings = this.childrenOf.get(parentRecord) ?? [];
      siblings.push(loc);
      this.childrenOf.set(parentRecord, siblings);
    }
    for (const loc of inModule.records) {
      this.collectRecordImports(loc.record);
    }
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
//  |  _  \\                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
//
// Generated by skir-zig-gen
// Home: https://github.com/gepheum/skir-zig-gen

`,
    );

    this.writeImports();

    for (const loc of this.childrenOf.get(null) ?? []) {
      this.writeRecord(loc);
    }

    return this.joinLinesAndFixFormatting();
  }

  private writeRecord(loc: RecordLocation): void {
    if (loc.record.recordType === "struct") {
      this.writeStruct(loc);
      return;
    }
    this.writeEnum(loc);
  }

  private writeImports(): void {
    this.push(
      `const skir_client = @import(${toZigStringLiteral(
        relativePathFromModule(this.inModule.path, null),
      )});\n`,
    );

    const importedModulePaths = [...this.referencedModulePaths].sort();
    for (const modulePath of importedModulePaths) {
      this.push(
        `const ${modulePathToImportAlias(modulePath)} = @import(${toZigStringLiteral(
          relativePathFromModule(this.inModule.path, modulePath),
        )});\n`,
      );
    }

    if (importedModulePaths.length > 0) {
      this.push("\n");
    } else {
      this.push("\n");
    }
  }

  private writeStruct(loc: RecordLocation): void {
    const typeName = getDeclaredTypeName(loc);
    const children = this.childrenOf.get(loc.record) ?? [];
    const keySpecs = this.keyedArrayContext.getKeySpecsForItemStruct(
      loc,
      this.typeSpeller,
    );

    this.push(commentify(docToCommentText(loc.record.doc)));
    this.push(`pub const ${typeName} = struct {\n`);

    for (const child of children) {
      this.writeRecord(child);
    }

    for (const field of loc.record.fields) {
      if (field.isRecursive !== false) {
        this.writeRecursiveFieldType(field);
      }
    }

    for (const field of loc.record.fields) {
      this.writeStructField(field);
    }

    this.push(`_unrecognized: ?skir_client.UnrecognizedFields = null,\n`);
    this.push(`pub const default: @This() = .{\n`);
    for (const field of loc.record.fields) {
      if (field.isRecursive !== false) {
        this.push(
          `.${this.getRecursiveStorageName(field)} = .default_value,\n`,
        );
      } else {
        this.push(
          `.${toStructFieldName(field.name.text)} = ${this.typeSpeller.getDefaultExpr(field.type!)},\n`,
        );
      }
    }
    this.push(`._unrecognized = null,\n`);
    this.push(`};\n`);

    const recursiveFields = loc.record.fields.filter(
      (field) => field.isRecursive !== false,
    );
    if (recursiveFields.length > 0) {
      for (const field of recursiveFields) {
        this.writeRecursiveFieldGetter(field);
      }
    }

    this.push(`};\n`);

    if (keySpecs.length > 0) {
      this.push(`\n`);
      for (const keySpec of keySpecs) {
        this.writeKeySpec(keySpec);
      }
    }
  }

  private writeEnum(loc: RecordLocation): void {
    const typeName = getDeclaredTypeName(loc);
    const children = this.childrenOf.get(loc.record) ?? [];
    const emitKindEnum = this.keyedArrayContext.isEnumUsedAsKey(loc.record);

    this.push(commentify(docToCommentText(loc.record.doc)));
    this.push(`pub const ${typeName} = union(enum) {\n`);

    for (const child of children) {
      this.writeRecord(child);
    }

    if (emitKindEnum) {
      this.push(`pub const Kind = enum {\n`);
      this.push(`${GENERATED_UNKNOWN_VARIANT_NAME},\n`);
      for (const variant of loc.record.fields) {
        this.push(`${toVariantName(variant.name.text)},\n`);
      }
      this.push(`};\n`);
    }

    this.push(
      `pub const default: @This() = .{ .${GENERATED_UNKNOWN_VARIANT_NAME} = .{} };\n`,
    );
    if (emitKindEnum) {
      this.push(`pub fn kind(self: @This()) Kind {\n`);
      this.push(`return switch (self) {\n`);
      this.push(
        `.${GENERATED_UNKNOWN_VARIANT_NAME} => .${GENERATED_UNKNOWN_VARIANT_NAME},\n`,
      );
      for (const variant of loc.record.fields) {
        const variantName = toVariantName(variant.name.text);
        this.push(`.${variantName} => .${variantName},\n`);
      }
      this.push(`};\n`);
      this.push(`}\n`);
    }

    this.push(
      `${GENERATED_UNKNOWN_VARIANT_NAME}: skir_client.UnrecognizedVariant,\n`,
    );
    for (const variant of loc.record.fields) {
      this.push(commentify(docToCommentText(variant.doc)));
      if (variant.type) {
        const variantType =
          variant.isRecursive !== false
            ? `*const ${this.typeSpeller.getZigType(variant.type)}`
            : this.typeSpeller.getZigType(variant.type);
        this.push(`${toVariantName(variant.name.text)}: ${variantType},\n`);
      } else {
        this.push(`${toVariantName(variant.name.text)},\n`);
      }
    }
    this.push(`};\n`);
  }

  private writeStructField(field: Field): void {
    const comment = commentify(docToCommentText(field.doc));

    if (field.isRecursive !== false) {
      const storageName = this.getRecursiveStorageName(field);
      this.push(comment);
      this.push(`${storageName}: ${this.getRecursiveTypeName(field)},\n`);
      return;
    }

    const fieldName = toStructFieldName(field.name.text);
    const fieldType = this.typeSpeller.getZigType(field.type!);
    this.push(comment);
    this.push(`${fieldName}: ${fieldType},\n`);
  }

  private writeRecursiveFieldGetter(field: Field): void {
    const getterName = toFieldGetterName(field);
    const storageName = this.getRecursiveStorageName(field);
    const returnType = this.typeSpeller.getZigType(field.type!);
    const defaultExpr = this.typeSpeller.getDefaultExpr(field.type!);

    this.push(commentify(docToCommentText(field.doc)));
    this.push(`pub fn ${getterName}(self: *const @This()) ${returnType} {\n`);
    this.push(`return switch (self.${storageName}) {\n`);
    this.push(`.default_value => ${defaultExpr},\n`);
    this.push(`.value => |value| value.*,\n`);
    this.push(`};\n`);
    this.push(`}\n`);
  }

  private writeRecursiveFieldType(field: Field): void {
    const recursiveTypeName = this.getRecursiveTypeName(field);
    const rawType = this.typeSpeller.getZigType(field.type!);

    this.push(`pub const ${recursiveTypeName} = union(enum) {\n`);
    this.push(`default_value,\n`);
    this.push(`value: *const ${rawType},\n`);
    this.push(`};\n`);
  }

  private writeKeySpec(keySpec: KeySpec): void {
    this.push(`pub const ${keySpec.specName} = struct {\n`);
    this.push(`pub const Value = ${keySpec.valueType};\n`);
    this.push(`pub const Key = ${keySpec.zigKeyType};\n`);
    this.push(`pub fn getGet(item: Value) Key {\n`);
    this.push(`return ${keySpec.zigKeyExpr};\n`);
    this.push(`}\n`);
    this.push(`pub fn defaultValue() *Value {\n`);
    this.push(`return @constCast(&Value.default);\n`);
    this.push(`}\n`);
    this.push(`pub fn keyExtractor() []const u8 {\n`);
    this.push(`return ${toZigStringLiteral(keySpec.keyExtractor)};\n`);
    this.push(`}\n`);
    this.push(`};\n`);
  }

  private getRecursiveStorageName(field: Field): string {
    return `_${toStructFieldName(field.name.text)}`;
  }

  private getRecursiveTypeName(field: Field): string {
    return `${toTypeName(field.name.text)}Recursive`;
  }

  private collectRecordImports(record: Record): void {
    for (const field of record.fields) {
      if (field.type) {
        this.collectTypeImports(field.type);
      }
    }
  }

  private collectTypeImports(type: ResolvedType): void {
    switch (type.kind) {
      case "primitive":
        return;
      case "optional":
        this.collectTypeImports(type.other);
        return;
      case "array":
        this.collectTypeImports(type.item);
        if (type.key?.keyType.kind === "record") {
          this.collectTypeImports(type.key.keyType);
        }
        return;
      case "record": {
        const recordLocation = this.typeSpeller.recordMap.get(type.key)!;
        if (recordLocation.modulePath !== this.inModule.path) {
          this.referencedModulePaths.add(recordLocation.modulePath);
        }
      }
    }
  }

  private push(...code: string[]): void {
    this.code += code.join("");
  }

  private joinLinesAndFixFormatting(): string {
    const indentUnit = "  ";
    let result = "";
    // The indent at every line is obtained by repeating indentUnit N times,
    // where N is the length of this array.
    const contextStack: Array<"{" | "(" | "[" | "<" | ":" | "."> = [];
    // Returns the last element in `contextStack`.
    const peakTop = (): string | undefined =>
      contextStack[contextStack.length - 1];
    const getMatchingLeftBracket = (r: "}" | ")" | "]" | ">"): string => {
      switch (r) {
        case "}":
          return "{";
        case ")":
          return "(";
        case "]":
          return "[";
        case ">":
          return "<";
      }
    };
    for (let line of this.code.split("\n")) {
      line = line.trim();
      if (line.length <= 0) {
        // Don't indent empty lines.
        result += "\n";
        continue;
      }

      const firstChar = line[0];
      switch (firstChar) {
        case "}":
        case ")":
        case "]":
        case ">": {
          const left = getMatchingLeftBracket(firstChar);
          while (contextStack.pop() !== left) {
            if (contextStack.length <= 0) {
              throw Error();
            }
          }
          break;
        }
        case ".": {
          if (peakTop() !== ".") {
            contextStack.push(".");
          }
          break;
        }
      }
      const indent =
        indentUnit.repeat(contextStack.length) +
        (line.startsWith("*") ? " " : "");
      result += `${indent}${line.trimEnd()}\n`;
      if (line.startsWith("//") || line.startsWith("*")) {
        // A comment.
        continue;
      }
      const lastChar = line.slice(-1);
      switch (lastChar) {
        case "{":
        case "(":
        case "[":
        case "<": {
          // The next line will be indented
          contextStack.push(lastChar);
          break;
        }
        case ":":
        case "=": {
          if (peakTop() !== ":") {
            contextStack.push(":");
          }
          break;
        }
        case ";":
        case ",": {
          if (peakTop() === "." || peakTop() === ":") {
            contextStack.pop();
          }
        }
      }
    }

    return (
      result
        // Remove spaces enclosed within curly brackets if that's all there is.
        .replace(/\{\s+\}/g, "{}")
        // Remove spaces enclosed within round brackets if that's all there is.
        .replace(/\(\s+\)/g, "()")
        // Remove spaces enclosed within square brackets if that's all there is.
        .replace(/\[\s+\]/g, "[]")
        // Remove empty line following an open curly bracket.
        .replace(/(\{\n *)/g, "$1")
        // Remove empty line preceding a closed curly bracket.
        .replace(/\n(\n *\})/g, "$1")
        // Coalesce consecutive empty lines.
        .replace(/\n\n\n+/g, "\n\n")
        // Remove trailing newline.
        .replace(/\n\n$/g, "\n")
    );
  }
}

function relativePathFromModule(
  fromModulePath: string,
  toModulePath: string | null,
): string {
  const fromFile = `src/skirout/${modulePathToOutputPath(fromModulePath)}`;
  const toFile = toModulePath
    ? `src/skirout/${modulePathToOutputPath(toModulePath)}`
    : "src/skir_client.zig";
  const fromDir = fromFile.slice(0, fromFile.lastIndexOf("/"));
  const fromParts = fromDir.split("/");
  const toParts = toFile.split("/");
  let common = 0;
  while (common < fromParts.length && fromParts[common] === toParts[common]) {
    common++;
  }
  const up = fromParts.length - common;
  const rel = [...Array(up).fill(".."), ...toParts.slice(common)].join("/");
  return rel.length > 0 ? rel : ".";
}

function commentify(text: string, indent = ""): string {
  if (!text) {
    return "";
  }
  return text
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line) => `${indent}/// ${line.trim()}\n`)
    .join("");
}

function docToCommentText(doc: { text: string }): string {
  return doc.text.trim();
}

function toZigStringLiteral(input: string): string {
  return JSON.stringify(input);
}

export const GENERATOR = new ZigCodeGenerator();
